name: dart_filter
description: High Level Filter Queries for Dart inspired by the Filter Pattern
version: 1.1.0+4
author: Modestas Valauskas <valauskasmodestas+dartpub@gmail.com>
homepage: https://github.com/modulovalue/dart_filter
repository: https://github.com/modulovalue/dart_filter
issue_tracker: https://github.com/modulovalue/dart_filter/issues

environment:
  sdk: '>2.2.2 <3.0.0'

dev_dependencies:
  extra_pedantic: ^1.0.0
  test: ^1.6.6
  test_coverage: ^0.2.0
  dart_coveralls: ^0.6.0